version: "3.0"

services:
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./dist:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 2020:80